In [1]:
import pandas as pd
import os

In [2]:
PATH_PER_WEEK = '../data_jeannie/per_week/'
PATH_FINAL = '../data_jeannie/final/'

In [2]:
PATH_PER_WEEK = '../data/per_week/'
PATH_FINAL = '../data/final/'

In [3]:
all_players_data= []
for week in os.listdir(PATH_PER_WEEK):
    path = PATH_PER_WEEK+'/'+week
    
    myplayers=pd.read_excel(path+'/my_players.xlsx',index_col='id')
    otherplayers=pd.read_excel(path+'/other_players.xlsx',index_col='id')
    
    myplayers['owned']='OUI'
    otherplayers['owned']='NON'
    myplayers['date']=week
    otherplayers['date']=week
    all_players_data.append(myplayers)
    all_players_data.append(otherplayers)
all_players = pd.concat(all_players_data)

In [4]:
MAX_DATE = all_players['date'].max()
MAX_DATE

'2024-02-07'

In [5]:
path_dir_out = PATH_FINAL +f'/{MAX_DATE}/'
file_name_out =  'all.xlsx'
os.makedirs(path_dir_out,exist_ok=True)
all_players.to_excel(path_dir_out+'/'+file_name_out)

---
# ANALYSIS

In [6]:
print(all_players.columns)

Index(['role', 'name', 'club', 'etranger', 'Price', 'HM points',
       'HM points AVG', 'Appareances', 'Goal', 'Goal OT', 'Assist #1',
       'Assist #2', 'Assist OT', 'Points', 'GWG', 'Penalties', '+/-', 'Shots',
       'Goals Ag.', 'Saves Nr.', 'Saves', 'owned', 'date', 'Ownership'],
      dtype='object')

In [7]:
analysis_df = all_players[all_players['date']==MAX_DATE]

In [8]:
analysis_df.loc[:,'VALUE_DIFF'] = analysis_df['HM points AVG']- analysis_df['Price']

C:\Users\lvg\AppData\Local\Temp\ipykernel_13948\3470102984.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  analysis_df.loc[:,'VALUE_DIFF'] = analysis_df['HM points AVG']- analysis_df['Price']

## Player to buy !

In [9]:
analysis_df[ (~pd.isnull(analysis_df['HM points']) ) & (analysis_df['owned'] =='NON' )
            ].nlargest(20, 'VALUE_DIFF')[['role','name','club','Price','HM points','HM points AVG','VALUE_DIFF','Appareances']]

,role,name,club,Price,HM points,HM points AVG,VALUE_DIFF,Appareances
id,,,,,,,,
848,DF,Y. Lichtensteiger,DAV,1.0,12.0,6.0,5.0,2.0
751,FW,S. Näf,BER,1.0,12.0,6.0,5.0,2.0
875,DF,N. Balestra,ZUG,1.0,28.0,5.6,4.6,5.0
886,DF,J. Schwendeler,ZSC,1.0,38.0,4.8,3.8,8.0
476,DF,A. Villa,LUG,1.5,19.0,4.8,3.3,4.0
755,DF,A. Nussbaumer,ZUG,3.0,12.0,6.0,3.0,2.0
877,DF,N. Rhyn,BER,1.0,7.0,3.5,2.5,2.0
871,DF,B. Sansonnens,FRI,1.0,14.0,3.5,2.5,4.0
46,FW,M. Künzle,BIE,5.5,176.0,7.7,2.2,23.0
746,FW,A. Guignard,GEN,1.0,15.0,3.0,2.0,5.0
680,FW,M. Spacek,AMB,10.5,495.0,12.4,1.9,40.0
15,FW,D. Rohrbach,LAN,3.0,215.0,4.8,1.8,45.0
34,DF,I. Jelovac,LAU,3.5,148.0,4.9,1.4,30.0
795,FW,R. Balcers,ZSC,9.0,428.0,10.2,1.2,42.0
882,FW,Y. Sablatnig,BER,1.0,25.0,2.1,1.1,12.0
794,FW,D. Malgin,ZSC,11.0,481.0,12.0,1.0,40.0
704,FW,J. Ang,KLO,7.0,351.0,8.0,1.0,44.0
475,DF,B. Wolf,LUG,6.5,301.0,7.5,1.0,40.0
479,FW,G. Wetter,RAP,2.0,108.0,3.0,1.0,36.0
851,FW,J. Luoto,BER,8.0,331.0,8.9,0.9,37.0

## Player to buy in range!

In [12]:
MIN_PRICE = 4
MAX_PRICE = 5.5

analysis_df[ (~pd.isnull(analysis_df['HM points']) ) & (analysis_df['owned'] =='NON' ) 
                & (analysis_df['Price'] >=MIN_PRICE )& (analysis_df['Price'] <=MAX_PRICE  )
            ].nlargest(20, 'VALUE_DIFF')[['role','name','club','Price','HM points','HM points AVG','VALUE_DIFF','Appareances']]

,role,name,club,Price,HM points,HM points AVG,VALUE_DIFF,Appareances
id,,,,,,,,
46,FW,M. Künzle,BIE,5.5,176.0,7.7,2.2,23.0
856,FW,S. Mäenalanen,LAN,5.0,220.0,5.8,0.8,38.0
830,FW,V. Rohrer,ZSC,4.0,198.0,4.8,0.8,41.0
105,FW,Y. Albrecht,RAP,5.5,234.0,6.2,0.7,38.0
402,FW,T. Bader,BER,5.5,235.0,6.2,0.7,38.0
708,DF,D. Reinbacher,KLO,5.5,174.0,6.2,0.7,28.0
255,DF,M. Völlmin,GEN,4.0,203.0,4.7,0.7,43.0
217,FW,H. Pesonen,LAN,5.5,257.0,6.1,0.6,42.0
414,DF,L. Profico,KLO,4.5,225.0,5.1,0.6,44.0
103,FW,Y. Zehnder,ZSC,4.5,177.0,5.1,0.6,35.0
718,FW,M. Marchon,KLO,4.0,192.0,4.6,0.6,42.0
98,FW,D. Lammer,RAP,4.5,217.0,4.9,0.4,44.0
469,DF,B. Guggenheim,LAN,4.0,145.0,4.4,0.4,33.0
580,DF,M. Müller,LUG,5.5,259.0,5.8,0.3,45.0
437,DF,Z. Dotti,AMB,5.0,170.0,5.3,0.3,32.0
627,FW,P. Devos,AJO,4.5,138.0,4.8,0.3,29.0
412,DF,F. Maier,RAP,4.5,211.0,4.8,0.3,44.0
61,DF,C. Paschoud,BER,4.5,152.0,4.8,0.3,32.0
737,DF,J. Peltonen,LUG,4.5,215.0,4.8,0.3,45.0
257,DF,E. Guebey,DAV,4.0,112.0,4.3,0.3,26.0

## Player to Sell!

In [10]:
analysis_df[ (~pd.isnull(analysis_df['HM points']) ) & (analysis_df['owned'] =='OUI' )
            ].nsmallest(20, 'VALUE_DIFF')[['role','name','club','Price','HM points','HM points AVG','VALUE_DIFF','Appareances']]

,role,name,club,Price,HM points,HM points AVG,VALUE_DIFF,Appareances
id,,,,,,,,
251,GK,Descloux / Mayer,GEN,9.0,213.0,5.0,-4.0,43.0
113,GK,Berra / Rüegger,FRI,14.0,455.0,10.3,-3.7,44.0
260,FW,F. Herzog,ZUG,12.5,483.0,11.2,-1.3,43.0
364,FW,T. Rajala,BIE,13.0,495.0,11.8,-1.2,42.0
454,FW,C. Thürkauf,LUG,16.0,686.0,15.2,-0.8,45.0
337,FW,S. Senteler,ZUG,8.5,255.0,7.7,-0.8,33.0
95,DF,R. Diaz,FRI,7.0,267.0,6.4,-0.6,42.0
130,FW,K. Mottet,FRI,7.5,301.0,7.0,-0.5,43.0
812,FW,M. Joly,LUG,15.5,634.0,15.1,-0.4,42.0
673,FW,J. de la Rose,FRI,10.0,424.0,9.6,-0.4,44.0
845,DF,L. Muggli,ZUG,8.5,271.0,8.2,-0.3,33.0
569,FW,M. Holdener,LAU,3.0,109.0,2.7,-0.3,40.0
609,DF,Y. Weber,ZSC,6.5,279.0,6.3,-0.2,44.0
104,FW,L. Martschini,ZUG,13.5,573.0,13.3,-0.2,43.0
806,DF,J. Honka,GEN,10.5,404.0,10.4,-0.1,39.0
791,DF,D. Ustinkov,ZSC,5.5,92.0,5.4,-0.1,17.0
226,DF,Y. Burren,BIE,5.0,181.0,4.9,-0.1,37.0
216,FW,C. Bertschy,FRI,11.5,504.0,11.5,0.0,44.0
200,DF,D. Trutmann,ZSC,4.5,177.0,4.7,0.2,38.0
416,DF,D. Egli,DAV,11.5,429.0,11.9,0.4,36.0

In [27]:
analysis_df[ (~pd.isnull(analysis_df['HM points']) ) & (analysis_df['owned'] =='OUI' )
            ].nsmallest(20, 'Appareances')[['role','name','club','Price','HM points','HM points AVG','VALUE_DIFF','Appareances']]

,role,name,club,Price,HM points,HM points AVG,VALUE_DIFF,Appareances
id,,,,,,,,
699,FW,M. Alge,RAP,1.0,5.0,1.0,0.0,5.0
823,DF,B. Zanetti,LAN,4.5,56.0,4.3,-0.2,13.0
52,FW,G. Kohler,AJO,3.5,56.0,3.7,0.2,15.0
625,FW,S. Macquat,AJO,2.5,35.0,2.3,-0.2,15.0
38,DF,M. Dufner,FRI,5.0,76.0,4.8,-0.2,16.0
482,DF,D. Wüthrich,AMB,4.0,69.0,4.1,0.1,17.0
672,FW,M. Sörensen,FRI,16.5,333.0,16.7,0.2,20.0
292,FW,C. DiDomenico,FRI,15.0,279.0,14.0,-1.0,20.0
113,GK,Berra / Rüegger,FRI,14.0,215.0,10.8,-3.2,20.0
801,DF,A. Borgman,FRI,14.0,277.0,13.9,-0.1,20.0
278,GK,Boltshauser / Charlin,LAN,12.0,159.0,8.0,-4.0,20.0
216,FW,C. Bertschy,FRI,11.5,226.0,11.3,-0.2,20.0
375,DF,R. Gunderson,FRI,11.0,208.0,10.4,-0.6,20.0
673,FW,J. de la Rose,FRI,10.0,201.0,10.1,0.1,20.0
798,FW,T. Rochette,LAU,9.0,176.0,8.8,-0.2,20.0
32,DF,B. Jecker,FRI,7.0,138.0,6.9,-0.1,20.0
357,FW,N. Marchon,FRI,7.0,138.0,6.9,-0.1,20.0
129,FW,J. Sprunger,FRI,7.0,143.0,7.2,0.2,20.0
95,DF,R. Diaz,FRI,6.0,116.0,5.8,-0.2,20.0
569,FW,M. Holdener,LAU,4.0,76.0,3.8,-0.2,20.0

In [28]:
analysis_df[ (~pd.isnull(analysis_df['HM points']) ) & (analysis_df['owned'] =='NON' ) & (analysis_df['Price'] <3)
            ].nlargest(20, 'Appareances')[['role','name','club','Price','HM points','HM points AVG','VALUE_DIFF','Appareances']]

,role,name,club,Price,HM points,HM points AVG,VALUE_DIFF,Appareances
id,,,,,,,,
716,FW,S. Kellenberger,KLO,2.5,46.0,2.3,-0.2,20.0
15,FW,D. Rohrbach,LAN,2.5,49.0,2.5,0.0,20.0
160,FW,J. Walker,LUG,2.5,51.0,2.6,0.1,20.0
267,FW,J. Wick,RAP,2.5,56.0,2.8,0.3,20.0
81,FW,M. Jörg,FRI,2.0,43.0,2.2,0.2,20.0
470,FW,J. Salzgeber,LAN,2.0,41.0,2.1,0.1,20.0
720,FW,H. Schreiber,KLO,2.0,42.0,2.1,0.1,20.0
643,FW,O. Lapinskis,LAN,1.5,33.0,1.7,0.2,20.0
559,FW,F. Ritzmann,BER,1.5,26.0,1.3,-0.2,20.0
244,FW,P. Berger,LAN,1.0,-9.0,-0.5,-1.5,20.0
110,FW,S. Zangger,RAP,1.0,20.0,1.0,0.0,20.0
394,FW,M. Miranda,GEN,2.5,48.0,2.5,0.0,19.0
738,FW,D. Binias,FRI,2.0,39.0,2.1,0.1,19.0
389,FW,S. Leuenberger,ZUG,2.0,34.0,1.8,-0.2,19.0
44,FW,R. Tanner,BIE,2.0,36.0,1.9,-0.1,19.0
501,FW,E. Schläpfer,BIE,1.5,29.0,1.5,0.0,19.0
717,FW,K. Lindemann,KLO,1.0,17.0,0.9,-0.1,19.0
324,FW,R. Prassl,DAV,1.0,17.0,0.9,-0.1,19.0
343,FW,C. Egli,DAV,2.5,41.0,2.3,-0.2,18.0
770,FW,M. Zanetti,LUG,2.5,49.0,2.7,0.2,18.0